import type { Locale } from "@/i18n/messages";

const COPY = {
  title: ["SmarTAI 补全缺失项", "Generate Missing Materials with SmarTAI"],
  cardTitle: ["确认补全范围", "Confirm Completion Scope"],
  cardDescription: ["预检不会调用模型。请先确认将生成的题目与资料槽位，确认后才开始生成。", "This review does not call a model. Confirm the questions and material fields before generation starts."],
  summaryQuestions: ["涉及题目", "Questions"],
  summaryMissing: ["缺失槽位", "Missing slots"],
  scopeTitle: ["将生成以下内容", "Generate the following content"],
  scopeDescription: ["默认选中当前全部缺失项；可以取消不希望本次生成的项目。", "All currently missing items are selected by default. Clear any item you do not want to generate now."],
  selectAll: ["全选", "Select all"],
  clearAll: ["清空", "Clear"],
  columnQuestion: ["题目", "Question"],
  columnType: ["题型", "Type"],
  columnTarget: ["缺失资料", "Missing material"],
  targetCriterion: ["评分标准", "Grading rubric"],
  targetAnswer: ["标答", "Reference answer"],
  targetCode: ["示例正确代码", "Reference solution code"],
  targetTests: ["测试样例", "Test cases"],
  testsPerQuestion: ["每道编程题生成测试样例", "Test cases per programming question"],
  testsCountSuffix: [" 个", ""],
  selectedPrefix: ["已选择 ", ""],
  selectedSuffix: [" 项", " selected"],
  missingOnlyTitle: ["只补缺失，不覆盖", "Missing only, never overwrite"],
  missingOnlyDescription: ["开始后即使教师并发补充了内容，系统也会跳过该槽位；SmarTAI 生成结果会标记为待确认。", "If a teacher fills a slot while generation is running, that slot is skipped. SmarTAI-generated content is marked for confirmation."],
  noMissingTitle: ["当前没有可补全的缺失项", "No missing materials to generate"],
  noMissingDescription: ["返回题目准备总览继续校对，或手动编辑已有资料。", "Return to Question Preparation to continue reviewing, or edit the existing materials manually."],
  loadErrorTitle: ["无法读取缺失项", "Missing materials could not be loaded"],
  loadErrorDescription: ["任务状态可能已变化。刷新后仍失败时，请从题目准备总览重新进入。", "The task may have changed. If refreshing does not help, reopen this flow from Question Preparation."],
  modelLoading: ["正在读取可用模型…", "Loading available models…"],
  modelUnavailableTitle: ["无法确认模型状态", "Model status could not be verified"],
  modelUnavailableDescription: ["为避免启动后立即失败，请先刷新模型状态或检查模型与 BYOK。", "To avoid an immediate failure, refresh model status or check Models & BYOK first."],
  modelMissingTitle: ["需要可用模型或 BYOK", "An available model or BYOK is required"],
  modelMissingDescription: ["当前没有已启用模型。缺失项预检仍可查看，但开始生成前需要先配置模型。", "No model is enabled. You can still review preflight, but a model must be configured before generation starts."],
  configureModels: ["前往模型与 BYOK", "Open Models & BYOK"],
  confirm: ["确认并开始生成", "Confirm & Generate"],
  confirming: ["正在启动…", "Starting…"],
  backOverview: ["返回题目准备总览", "Back to Question Preparation"],
  refresh: ["刷新", "Refresh"],
  selectionRequired: ["请至少选择一个缺失项。", "Select at least one missing item."],
  startErrorGeneric: ["暂时无法开始生成。请刷新缺失项后重试。", "Generation could not start. Refresh the missing items and try again."],
  errorTaskNotReady: ["只有题目准备阶段可以补全缺失资料。", "Missing materials can only be generated during Question Preparation."],
  errorStale: ["题目资料已变化，请刷新并重新确认补全范围。", "Question materials changed. Refresh and confirm the scope again."],
  errorBusy: ["任务正在执行其他操作，请等待完成后再试。", "The task is busy with another operation. Try again when it finishes."],
  errorUnknownTarget: ["部分缺失项已变化，请刷新并重新选择。", "Some missing items changed. Refresh and select again."],
  scopeRefreshed: ["题目资料已变化，补全范围已刷新。请核对新范围后再次确认。", "Question materials changed, so the generation scope was refreshed. Review the new scope before confirming again."],
  errorModel: ["当前没有可用模型，请先检查模型与 BYOK 配置。", "No model is currently available. Check Models & BYOK first."],
  leaveTitle: ["离开 SmarTAI 补全？", "Leave SmarTAI Completion?"],
  leaveDescription: ["当前选择尚未启动，离开后需要重新确认补全范围。", "Generation has not started. You will need to confirm the scope again after leaving."],
  stay: ["继续确认", "Keep Reviewing"],
  leave: ["放弃并离开", "Leave"],
  progressTitle: ["SmarTAI 补全进度", "SmarTAI Completion Progress"],
  progressHeading: ["正在生成缺失资料", "Generating Missing Materials"],
  progressBackground: ["可以离开本页，生成会在后台继续；完成后将自动返回题目准备总览。", "You can leave this page while generation continues. When complete, you will return to Question Preparation automatically."],
  progressLabel: ["SmarTAI 补全进度", "SmarTAI completion progress"],
  processing: ["处理中", "Processing"],
  stepsTitle: ["生成步骤", "Generation steps"],
  stepScope: ["确认补全范围", "Confirm completion scope"],
  stepGenerate: ["生成缺失内容", "Generate missing content"],
  stepValidate: ["校验生成结构", "Validate generated structure"],
  stepSave: ["写回仍为空的槽位", "Save into still-empty slots"],
  latestEvents: ["最新进展", "Latest updates"],
  waitingEvents: ["正在等待生成事件…", "Waiting for generation events…"],
  runInBackground: ["返回工作台", "Back to Workspace"],
  viewTasks: ["查看历史任务", "View Task History"],
  progressFailedTitle: ["SmarTAI 补全未完成", "SmarTAI Completion Did Not Finish"],
  progressFailedDescription: ["已生成但未安全写回的内容不会覆盖题目资料。请检查模型配置后重新选择缺失项。", "Content that was not safely saved will not overwrite question materials. Check the model configuration and select the missing items again."],
  chooseAgain: ["重新选择缺失项", "Choose Missing Items Again"],
  progressReadFailedTitle: ["无法读取生成状态", "Generation status could not be loaded"],
  progressReadFailedDescription: ["任务不会因离开页面而停止。请刷新状态，或从题目准备总览重新进入。", "Leaving the page does not stop the job. Refresh the status or reopen it from Question Preparation."],
  jobMissing: ["缺少生成任务信息。", "Generation job information is missing."],
} as const;

export type AICompletionCopyKey = keyof typeof COPY;

export function aiCompletionText(locale: Locale, key: AICompletionCopyKey): string {
  return COPY[key][locale === "zh-CN" ? 0 : 1];
}
