import type { Locale } from "@/i18n/messages";

const COPY = {
  title: ["批改设置", "Grading Setup"],
  modelsTitle: ["批改模型", "Grading models"],
  modelsDescription: ["为本次正式批改选择模型；不会改变模型与 BYOK 页的全局启用状态。", "Choose models for this grading run without changing their global Models & BYOK state."],
  enabledConfiguration: ["已启用配置", "Enabled configuration"],
  disabledConfiguration: ["未启用", "Disabled"],
  invalidModelTitle: ["已保存模型已失效", "Saved model unavailable"],
  invalidModelDescription: ["取消选择，或选择新的已启用模型", "Deselect it or choose a new enabled model"],
  invalidModelRemoved: ["已移除失效模型，请选择一个已启用模型。", "The unavailable model was removed. Select an enabled model."],
  invalidModelsRemoved: ["选择新模型时已自动移除失效配置，请核对后保存。", "Unavailable configurations were removed when the new model was selected. Review before saving."],
  sharedModel: ["平台共享", "Shared pool"],
  primaryModel: ["主模型", "Primary"],
  providerSelectionRequired: ["请至少选择一个已启用模型。", "Select at least one enabled model."],
  providerStatusNote: ["“已启用”表示配置可被选择，不代表供应商实时在线。", "Enabled means the configuration can be selected; it does not verify the provider is online."],
  noModelsTitle: ["需要模型或 BYOK", "A model or BYOK is required"],
  noModelsDescription: ["当前没有已启用模型。可以先配置模型，返回后继续本任务。", "No model is enabled. Configure one, then return to continue this task."],
  configureModels: ["前往模型与 BYOK", "Open Models & BYOK"],
  aggregationTitle: ["多模型综合方式", "Multi-model synthesis"],
  singleMethod: ["单模型批改", "Single-model grading"],
  singleMethodDescription: ["仅调用所选模型。", "Only the selected model is called."],
  weightedMethod: ["置信度加权", "Confidence-weighted"],
  weightedDescription: ["按各模型置信度综合结果，默认更节约调用。", "Combine results by model confidence with fewer calls by default."],
  judgeMethod: ["综合评审", "Judge synthesis"],
  judgeDescription: ["由主模型再综合各模型结果。", "The primary model synthesizes all model results."],
  extraCall: ["额外模型调用", "Extra model call"],
  knowledgeTitle: ["任务资料范围", "Task knowledge scope"],
  knowledgeDescription: ["逐题已确认的评分标准、标答和测试样例始终参与；这里只决定是否加入本任务资料。", "Confirmed rubrics, answers, and tests always apply. Choose whether task documents are added."],
  knowledgeNone: ["不使用任务资料", "Do not use task documents"],
  knowledgeNoneDescription: ["仅使用题目及逐题已确认资料。", "Use only the problems and confirmed per-problem materials."],
  knowledgeAll: ["使用全部任务资料", "Use all task documents"],
  knowledgeAllPrefix: ["当前共 ", "Use all "],
  knowledgeAllSuffix: [" 份，批改时按当前任务检索。", " task document(s) during grading."],
  knowledgeEmptyWarning: ["当前任务还没有资料；保存后仍可继续，批改只使用题目及逐题资料。", "This task has no documents yet. You can still continue; grading will use the problems and confirmed per-problem materials."],
  strategyTitle: ["评分方式", "Grading approach"],
  strategyDescription: ["先保留常用设置；复核阈值、语言和多采样放在高级设置中。", "Common settings stay visible; review threshold, language, and sampling are under Advanced."],
  strictness: ["严格度", "Strictness"],
  lenient: ["较宽松", "Lenient"],
  standard: ["标准", "Standard"],
  strict: ["较严格", "Strict"],
  allowPartialCredit: ["允许部分分", "Allow partial credit"],
  allowPartialCreditDescription: ["根据有效步骤和评分标准给予过程分。", "Award credit for valid steps according to the rubric."],
  feedbackTone: ["评语语气", "Feedback tone"],
  toneEncouraging: ["鼓励", "Encouraging"],
  toneNeutral: ["中性", "Neutral"],
  toneStrict: ["严格", "Strict"],
  feedbackLength: ["评语长度", "Feedback length"],
  lengthShort: ["简短", "Short"],
  lengthMedium: ["适中", "Medium"],
  lengthLong: ["详细", "Detailed"],
  showAdvanced: ["展开高级设置", "Show advanced settings"],
  hideAdvanced: ["收起高级设置", "Hide advanced settings"],
  advancedSummaryThreshold: ["低置信阈值", "Low-confidence threshold"],
  advancedSummarySample: ["次采样", "sample(s)"],
  suggestCorrections: ["在评语中给出改进建议", "Suggest corrections in feedback"],
  feedbackLanguage: ["评语语言", "Feedback language"],
  languageChinese: ["中文", "Chinese"],
  languageEnglish: ["英文", "English"],
  lowConfidenceThreshold: ["低置信复核阈值", "Low-confidence review threshold"],
  lowConfidenceDescription: ["低于该值的结果进入优先复核范围。", "Results below this value are prioritized for review."],
  multiSample: ["单模型采样次数", "Single-model sample count"],
  multiSampleSuffix: [" 次", ""],
  multiSampleSharedDescription: ["平台共享模型固定为单次采样。", "Shared-pool models are limited to one sample."],
  multiSampleMultipleDescription: ["选择多个模型时，每个模型各运行一次。", "With multiple models, each model runs once."],
  multiSampleDescription: ["增加采样会增加模型调用，仅适用于单个自有模型。", "More samples increase model calls and apply only to one owner model."],
  teacherNotes: ["批改注意事项", "Teacher notes"],
  teacherNotesPlaceholder: ["例如：重点检查推导步骤；允许等价表述。", "For example: focus on derivation steps and accept equivalent wording."],
  charactersSuffix: [" 字", " characters"],
  backToQuestions: ["返回题目准备", "Back to Problem Preparation"],
  backToPrevious: ["返回上一页", "Back to Previous Page"],
  backToUpload: ["返回上传作答", "Back to Answer Upload"],
  saveAndContinue: ["保存设置并添加学生作答", "Save & Add Submissions"],
  saving: ["正在保存…", "Saving…"],
  loading: ["正在读取批改设置…", "Loading grading setup…"],
  loadErrorTitle: ["无法读取批改设置", "Grading setup could not be loaded"],
  loadErrorDescription: ["请检查连接后重试；当前任务内容不会被修改。", "Check the connection and try again. The task has not been changed."],
  retry: ["重新加载", "Reload"],
  refreshStatus: ["刷新状态", "Refresh status"],
  taskMissingTitle: ["缺少任务信息", "Task information is missing"],
  taskMissingDescription: ["请从题目准备总览重新进入批改设置。", "Open Grading Setup again from Problem Preparation."],
  invalidForm: ["请先完成模型选择并检查当前设置。", "Complete model selection and review the current settings."],
  workflowNotReady: ["当前任务还不能保存批改设置，请先完成题目准备。", "This task is not ready for grading setup. Finish Problem Preparation first."],
  workflowBusy: ["任务正在执行其他操作，请等待完成后再保存。", "The task is busy with another operation. Save after it finishes."],
  setupLocked: ["批改已开始，当前设置已锁定。", "Grading has started, so this setup is locked."],
  serverChangedWhileEditing: ["任务或模型配置已更新。当前编辑已保留，请核对后重新保存。", "The task or model configuration changed. Your edits were kept; review them before saving."],
  staleReloaded: ["任务内容已变化。当前编辑已保留并使用最新版本，请核对后重新保存。", "The task changed. Your edits were kept against the latest version; review them before saving again."],
  providerChanged: ["模型配置已变化，请重新选择模型。", "Model configuration changed. Select the models again."],
  sharedPoolRestriction: ["平台共享模型只能单独使用并固定单次采样。", "A shared-pool model must be used alone with one sample."],
  saveErrorGeneric: ["暂时无法保存批改设置，请稍后重试。", "Grading setup could not be saved. Try again shortly."],
  leaveTitle: ["离开批改设置？", "Leave Grading Setup?"],
  leaveDescription: ["当前修改尚未保存，离开后会丢失。", "Your changes have not been saved and will be lost."],
  stay: ["继续设置", "Keep editing"],
  leave: ["放弃并离开", "Leave without saving"],
} as const;

export type GradingSetupCopyKey = keyof typeof COPY;

export function gradingSetupText(locale: Locale, key: GradingSetupCopyKey): string {
  return COPY[key][locale === "zh-CN" ? 0 : 1];
}
