import type { Locale } from "@/i18n/messages";

export const materialImportCopy = {
  "zh-CN": {
    title: "批量导入资料",
    backToOverview: "返回题目准备总览",
    targetsTitle: "要导入什么？",
    targetRubric: "评分标准",
    targetAnswer: "标答",
    targetTests: "编程题测试样例",
    sourceTitle: "资料来源",
    sourceLibrary: "从课程资料库选择",
    sourceUpload: "上传新文件",
    selectedPrefix: "已选择：",
    noSource: "尚未选择资料",
    change: "更换",
    chooseFile: "选择文件",
    librarySearch: "搜索课程资料库",
    librarySearchPlaceholder: "搜索文件名",
    libraryEmpty: "没有找到可用资料",
    libraryError: "无法读取课程资料库",
    currentCourse: "当前课程",
    uncategorized: "未分类",
    allMine: "本人全部",
    saveToLibrary: "同时保存到课程资料库",
    structureTitle: "资料文件结构",
    organized: "已按题整理",
    organizedDescription: "适合本次作业逐题资料，系统匹配题号并整理格式。",
    extract: "从原文提取",
    extractDescription: "适合整本书答案或长文档，系统定位本次题目再提取。",
    hintLabel: "提取范围与题号说明（可选）",
    hintPlaceholder: "例如：第 7 章 1–15 题；仅提取课后练习，忽略例题",
    start: "开始导入并匹配到题目",
    checking: "正在检查资料…",
    starting: "正在开始导入…",
    taskUnavailable: "无法读取当前任务，请从工作台或历史任务重新进入。",
    taskNotReady: "请先完成题目识别与准备，再批量导入资料。",
    modelRequired: "请先配置并启用至少一个模型。",
    openByok: "前往模型与 BYOK",
    targetRequired: "请至少选择一种要导入的资料。",
    sourceRequired: "请选择课程资料或上传新文件。",
    unsupportedFile: "仅支持 PDF、TXT 或 Markdown 文件。",
    genericError: "暂时无法开始导入，请保留当前选择后重试。",
    leaveTitle: "离开批量导入？",
    leaveDescription: "当前资料选择尚未提交，离开后将丢失。",
    stay: "继续填写",
    leave: "放弃并离开",
    progressTitle: "资料导入进度",
    progressHeading: "正在匹配题目资料",
    progressFailedHeading: "资料匹配未完成",
    progressBackground: "可以离开此页，导入会在后台继续；完成候选匹配后将进入确认页。",
    progressSteps: "导入步骤",
    progressLatest: "最近进度",
    progressWaiting: "正在等待后端返回事实进度…",
    progressLoadError: "无法读取资料导入进度。",
    refresh: "刷新状态",
    backWorkspace: "返回工作台",
    chooseAgain: "重新选择资料",
    reviewTitle: "确认资料匹配",
    reviewDescription: "核对明确匹配、可能匹配和冲突项；默认不会覆盖现有内容。",
    reviewQuestion: "题目",
    reviewTarget: "资料类型",
    reviewMatch: "匹配状态",
    reviewPreview: "候选内容",
    reviewExisting: "现有内容",
    reviewAction: "应用",
    exact: "明确匹配",
    possible: "可能匹配",
    conflict: "存在冲突",
    selected: "导入",
    overwrite: "覆盖现有内容",
    noOverwrite: "保留现有内容",
    apply: "应用已确认的匹配",
    applying: "正在应用…",
    reviewEmpty: "当前导入没有可确认的候选项。",
    reviewLoadError: "无法读取资料匹配结果。",
    selectedCountPrefix: "已选择 ",
    selectedCountSuffix: " 项",
  },
  "en-US": {
    title: "Bulk Material Import",
    backToOverview: "Back to Problem Preparation",
    targetsTitle: "What do you want to import?",
    targetRubric: "Rubrics",
    targetAnswer: "Reference Answers",
    targetTests: "Programming Test Cases",
    sourceTitle: "Material Source",
    sourceLibrary: "Choose from Course Library",
    sourceUpload: "Upload New File",
    selectedPrefix: "Selected: ",
    noSource: "No material selected",
    change: "Change",
    chooseFile: "Choose File",
    librarySearch: "Search Course Library",
    librarySearchPlaceholder: "Search filenames",
    libraryEmpty: "No usable materials found",
    libraryError: "Course Library could not be loaded",
    currentCourse: "Current Course",
    uncategorized: "Uncategorized",
    allMine: "All Mine",
    saveToLibrary: "Also save to Course Library",
    structureTitle: "Material File Structure",
    organized: "Organized by Problem",
    organizedDescription: "Best for per-problem materials. The system matches problem numbers and cleans formatting.",
    extract: "Extract from Source",
    extractDescription: "Best for books or long documents. The system locates this assignment before extracting.",
    hintLabel: "Extraction scope and problem numbers (optional)",
    hintPlaceholder: "Example: Chapter 7, problems 1–15; exercises only, exclude examples",
    start: "Start Import & Match to Problems",
    checking: "Checking material…",
    starting: "Starting import…",
    taskUnavailable: "This task could not be loaded. Reopen it from Workspace or History.",
    taskNotReady: "Finish problem recognition and preparation before importing materials.",
    modelRequired: "Configure and enable at least one model first.",
    openByok: "Open Models & BYOK",
    targetRequired: "Select at least one material type.",
    sourceRequired: "Choose a Course Library material or upload a new file.",
    unsupportedFile: "Choose a PDF, TXT, or Markdown file.",
    genericError: "Import could not start. Keep your selections and retry.",
    leaveTitle: "Leave bulk import?",
    leaveDescription: "Your material selections have not been submitted and will be lost.",
    stay: "Keep Editing",
    leave: "Discard & Leave",
    progressTitle: "Material Import Progress",
    progressHeading: "Matching Materials to Problems",
    progressFailedHeading: "Material Matching Did Not Finish",
    progressBackground: "You may leave this page while import continues. Candidate review opens when matching is ready.",
    progressSteps: "Import Steps",
    progressLatest: "Latest Progress",
    progressWaiting: "Waiting for factual progress from the backend…",
    progressLoadError: "Material import progress could not be loaded.",
    refresh: "Refresh Status",
    backWorkspace: "Back to Workspace",
    chooseAgain: "Choose Material Again",
    reviewTitle: "Confirm Material Matches",
    reviewDescription: "Review exact, possible, and conflicting matches. Existing content is preserved by default.",
    reviewQuestion: "Problem",
    reviewTarget: "Material Type",
    reviewMatch: "Match",
    reviewPreview: "Candidate",
    reviewExisting: "Existing",
    reviewAction: "Apply",
    exact: "Exact Match",
    possible: "Possible Match",
    conflict: "Conflict",
    selected: "Import",
    overwrite: "Overwrite Existing Content",
    noOverwrite: "Keep Existing Content",
    apply: "Apply Confirmed Matches",
    applying: "Applying…",
    reviewEmpty: "This import has no candidates to review.",
    reviewLoadError: "Material match results could not be loaded.",
    selectedCountPrefix: "",
    selectedCountSuffix: " selected",
  },
} as const;

export type MaterialImportCopyKey = keyof typeof materialImportCopy["zh-CN"];

export function materialImportText(locale: Locale, key: MaterialImportCopyKey) {
  return materialImportCopy[locale][key];
}
